import { useState, useEffect, useRef, useCallback } from "react";
const T={bg:"#0B0E14",panel:"#131720",card:"#1A1F2E",cardHi:"#222839",border:"rgba(255,255,255,0.06)",borderHi:"rgba(255,255,255,0.12)",text:"#E2E8F0",sub:"#8892A8",dim:"#4A5568",blue:"#60A5FA",blueDim:"rgba(96,165,250,0.15)",green:"#34D399",greenDim:"rgba(52,211,153,0.12)",amber:"#FBBF24",amberDim:"rgba(251,191,36,0.12)",red:"#F87171",redDim:"rgba(248,113,113,0.12)",teal:"#2DD4BF",purple:"#A78BFA"};
function Panel({children,glow,style}){return <div style={{background:T.card,border:`1px solid ${glow||T.border}`,borderRadius:12,padding:14,boxShadow:glow?`0 0 24px ${glow}`:"none",transition:"all 0.3s",...style}}>{children}</div>}
function Badge({children,color}){return <span style={{display:"inline-block",fontSize:10,fontWeight:600,padding:"2px 8px",borderRadius:6,background:(color||T.blue)+"18",color:color||T.blue}}>{children}</span>}
function Bar({value,max,color,h}){return <div style={{height:h||6,background:T.panel,borderRadius:99,overflow:"hidden"}}><div style={{height:"100%",width:Math.min(100,Math.max(0,(value/(max||100))*100))+"%",background:color||T.blue,borderRadius:99,transition:"width 0.4s"}}/></div>}
function Num({value,label,icon,color,unit}){return <div style={{textAlign:"center"}}><div style={{fontSize:10,color:T.dim,marginBottom:2}}>{icon} {label}</div><div style={{fontSize:22,fontWeight:700,color:color||T.text,lineHeight:1}}>{value}{unit&&<span style={{fontSize:10,fontWeight:400,color:T.dim,marginLeft:2}}>{unit}</span>}</div></div>}
function Btn({children,onClick,on,color,big}){return <button onClick={onClick} style={{background:on?(color||T.blue)+"22":"transparent",border:`1px solid ${on?(color||T.blue)+"55":T.border}`,borderRadius:8,padding:big?"8px 20px":"6px 12px",fontSize:big?13:11,fontWeight:500,color:on?(color||T.blue):T.sub,cursor:"pointer",transition:"all 0.2s",fontFamily:"inherit"}}>{children}</button>}
function Log({items}){const ref=useRef(null);useEffect(()=>{if(ref.current)ref.current.scrollTop=ref.current.scrollHeight},[items]);return <div ref={ref} style={{background:T.bg,border:`1px solid ${T.border}`,borderRadius:10,padding:"8px 12px",maxHeight:160,overflowY:"auto",fontSize:11,lineHeight:1.8,marginTop:10,fontFamily:"'SF Mono',Consolas,monospace"}}>{items.length===0&&<span style={{color:T.dim}}>Waiting for events...</span>}{items.slice(-20).map((e,i)=><div key={i}><span style={{color:T.dim,opacity:.5}}>[{e.t}]</span>{" "}<span style={{color:e.c||T.sub}}>{e.m}</span></div>)}</div>}
function Tip({children}){return <div style={{background:T.blueDim,border:"1px solid rgba(96,165,250,0.15)",borderRadius:10,padding:"10px 14px",marginBottom:14,fontSize:12.5,lineHeight:1.6,color:"#93C5FD"}}>{children}</div>}

function Factory(){const init=[{n:"CNC Mill",ic:"⚙️",q:0,busy:false,done:0,avg:3,prog:0},{n:"Assembly",ic:"🔧",q:0,busy:false,done:0,avg:5,prog:0},{n:"QC Check",ic:"🔬",q:0,busy:false,done:0,avg:2,prog:0},{n:"Packing",ic:"📦",q:0,busy:false,done:0,avg:2,prog:0}];
const[st,setSt]=useState(init);const[clk,setClk]=useState(0);const[log,setLog]=useState([]);const[on,setOn]=useState(false);const[rate,setRate]=useState(3);const[ship,setShip]=useState(0);const ir=useRef(null);
const step=useCallback(()=>{setClk(c=>c+1);setSt(prev=>{const s=prev.map(x=>({...x}));const ev=[];const t=clk+1;if(Math.random()<rate/10){s[0].q++;ev.push({t:t+"s",m:"📥 New part arrived → "+s[0].n+" queue",c:T.blue})}for(let i=0;i<s.length;i++){if(s[i].busy){s[i].prog=Math.min(100,s[i].prog+(100/s[i].avg)*(0.5+Math.random()*0.7));if(s[i].prog>=100){s[i].busy=false;s[i].done++;s[i].prog=0;if(i<s.length-1){s[i+1].q++;ev.push({t:t+"s",m:"✅ "+s[i].n+" finished → sent to "+s[i+1].n,c:T.green})}else{setShip(v=>v+1);ev.push({t:t+"s",m:"🚀 Product shipped! ("+s[i].n+" complete)",c:T.teal})}}}if(!s[i].busy&&s[i].q>0){s[i].busy=true;s[i].q--;s[i].prog=5;ev.push({t:t+"s",m:s[i].ic+" "+s[i].n+" started processing",c:T.amber})}}if(ev.length)setLog(l=>[...l,...ev].slice(-50));return s})},[clk,rate]);
useEffect(()=>{if(on)ir.current=setInterval(step,500);else clearInterval(ir.current);return()=>clearInterval(ir.current)},[on,step]);
const reset=()=>{setOn(false);setClk(0);setLog([]);setShip(0);setSt(init)};const wip=st.reduce((a,x)=>a+x.q+(x.busy?1:0),0);
return <div><Tip><strong>How it works:</strong> Raw parts enter from the left and pass through 4 machines in order. Each machine works on one part at a time — others wait in a queue. When the last machine finishes, the product ships. Increase the arrival rate to see queues build up!</Tip>
<div style={{display:"flex",gap:8,marginBottom:14,flexWrap:"wrap"}}>{[{ic:"⏱",l:"Time",v:clk,u:"s"},{ic:"🚀",l:"Shipped",v:ship,c:T.green},{ic:"📊",l:"In Progress",v:wip,c:T.amber},{ic:"⚡",l:"Busy",v:st.filter(x=>x.busy).length+"/4",c:T.purple}].map((m,i)=><Panel key={i} style={{flex:"1 1 70px",padding:"10px 8px",textAlign:"center"}}><Num icon={m.ic} label={m.l} value={m.v} color={m.c} unit={m.u}/></Panel>)}</div>
<Panel style={{marginBottom:14,padding:14}}><div style={{display:"grid",gridTemplateColumns:"40px repeat(4,1fr) 40px",gap:6,alignItems:"center"}}>
<div style={{textAlign:"center"}}><div style={{fontSize:22}}>📥</div><div style={{fontSize:8,color:T.dim}}>IN</div></div>
{st.map((s,i)=><div key={i} style={{background:s.busy?T.amberDim:T.panel,border:`1px solid ${s.busy?T.amber+"40":T.border}`,borderRadius:10,padding:"12px 8px",textAlign:"center",transition:"all 0.4s"}}>
<div style={{fontSize:22,marginBottom:4}}>{s.ic}</div><div style={{fontSize:11,fontWeight:600,color:T.text,marginBottom:6}}>{s.n}</div>
<Bar value={s.busy?s.prog:0} max={100} color={s.busy?T.amber:T.green} h={5}/>
<div style={{display:"flex",justifyContent:"space-between",marginTop:5,fontSize:9,color:T.dim}}><span>🔄{s.q}</span><span>✅{s.done}</span></div>
{s.busy?<Badge color={T.amber}>Working...</Badge>:s.q>0?<Badge color={T.green}>Ready</Badge>:<Badge color={T.dim}>Idle</Badge>}
</div>)}
<div style={{textAlign:"center"}}><div style={{fontSize:22}}>🚀</div><div style={{fontSize:12,fontWeight:700,color:T.teal}}>{ship}</div></div>
</div></Panel>
<div style={{display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"}}><span style={{fontSize:11,color:T.sub}}>📈 Speed</span><input type="range" min="1" max="8" value={rate} step="1" onChange={e=>setRate(+e.target.value)} style={{flex:"1 1 60px",maxWidth:120,accentColor:T.blue}}/><span style={{fontSize:12,fontWeight:600,color:T.blue}}>{rate}/10</span>
<Btn onClick={()=>setOn(!on)} on={on} color={on?T.amber:T.green} big>{on?"⏸ Pause":"▶ Run"}</Btn><Btn onClick={step}>⏭</Btn><Btn onClick={reset}>🔄</Btn></div><Log items={log}/></div>}

function Traffic(){const[ph,setPh]=useState(0);const phR=useRef(0);const[qs,setQs]=useState({N:0,S:0,E:0,W:0});const[clk,setClk]=useState(0);const[log,setLog]=useState([]);const[on,setOn]=useState(false);const[passed,setPassed]=useState(0);const[gl,setGl]=useState(5);const ir=useRef(null);const isNS=ph===0;
const step=useCallback(()=>{setClk(c=>{const t=c+1;const ev=[];setQs(q=>{const nq={...q};if(Math.random()<0.45){const d=["N","S","E","W"][Math.floor(Math.random()*4)];nq[d]++;ev.push({t:t+"s",m:"🚗 Car arrived → "+d,c:T.blue})}const p=phR.current;const gd=p===0?["N","S"]:["E","W"];if(p===0||p===2){for(const d of gd){if(nq[d]>0&&Math.random()<0.55){nq[d]--;setPassed(v=>v+1);ev.push({t:t+"s",m:"✅ Car passed "+d+" (green light)",c:T.green})}}}return nq});if(t%(ph%2===0?gl:2)===0){phR.current=(phR.current+1)%4;setPh(phR.current);ev.push({t:t+"s",m:"🚦 Signal → "+["🟢 N-S GO","🟡 N-S Yellow","🟢 E-W GO","🟡 E-W Yellow"][phR.current],c:T.amber})}if(ev.length)setLog(l=>[...l,...ev].slice(-50));return t})},[gl,ph]);
useEffect(()=>{if(on)ir.current=setInterval(step,600);else clearInterval(ir.current);return()=>clearInterval(ir.current)},[on,step]);const reset=()=>{setOn(false);setClk(0);setPh(0);phR.current=0;setQs({N:0,S:0,E:0,W:0});setLog([]);setPassed(0)};const total=qs.N+qs.S+qs.E+qs.W;
return <div><Tip><strong>How it works:</strong> Cars arrive from 4 directions (North, South, East, West). The traffic light switches between letting North-South traffic go and East-West traffic go. Cars can only pass on green — otherwise they wait. Watch queues build up at red lights!</Tip>
<div style={{display:"flex",gap:8,marginBottom:14,flexWrap:"wrap"}}>{[{ic:"⏱",l:"Time",v:clk,u:"s"},{ic:"✅",l:"Passed",v:passed,c:T.green},{ic:"🚗",l:"Waiting",v:total,c:total>8?T.red:T.amber},{ic:"🚦",l:"Light",v:isNS?"↕ NS":"↔ EW",c:T.blue}].map((m,i)=><Panel key={i} style={{flex:"1 1 70px",padding:"10px 8px",textAlign:"center"}}><Num icon={m.ic} label={m.l} value={m.v} color={m.c} unit={m.u}/></Panel>)}</div>
<Panel style={{marginBottom:14,padding:12,display:"flex",justifyContent:"center"}}><svg viewBox="0 0 300 300" width="100%" style={{maxWidth:320,display:"block"}}><rect x="115" y="0" width="70" height="300" fill={T.cardHi} rx="3"/><rect x="0" y="115" width="300" height="70" fill={T.cardHi} rx="3"/><rect x="115" y="115" width="70" height="70" fill={T.panel}/>
{[30,55,80,220,245,270].map(y=><line key={"v"+y} x1="150" y1={y} x2="150" y2={y+12} stroke={T.dim} strokeWidth="1" opacity=".3"/>)}{[30,55,80,220,245,270].map(x=><line key={"h"+x} x1={x} y1="150" x2={x+12} y2="150" stroke={T.dim} strokeWidth="1" opacity=".3"/>)}
<circle cx="110" cy="110" r="9" fill={isNS?T.green:T.red} opacity=".85"/><circle cx="190" cy="190" r="9" fill={isNS?T.green:T.red} opacity=".85"/><circle cx="190" cy="110" r="9" fill={!isNS?T.green:T.red} opacity=".85"/><circle cx="110" cy="190" r="9" fill={!isNS?T.green:T.red} opacity=".85"/>
<text x="150" y="22" textAnchor="middle" fill={T.text} fontSize="13" fontWeight="700">N: {qs.N}</text><text x="150" y="293" textAnchor="middle" fill={T.text} fontSize="13" fontWeight="700">S: {qs.S}</text><text x="22" y="154" textAnchor="middle" fill={T.text} fontSize="13" fontWeight="700">{qs.W}</text><text x="278" y="154" textAnchor="middle" fill={T.text} fontSize="13" fontWeight="700">{qs.E}</text>
<text x="150" y="40" textAnchor="middle" fill={isNS?T.green:T.red} fontSize="10">{isNS?"🟢 GO":"🔴 STOP"}</text><text x="150" y="276" textAnchor="middle" fill={isNS?T.green:T.red} fontSize="10">{isNS?"🟢 GO":"🔴 STOP"}</text><text x="50" y="108" textAnchor="middle" fill={!isNS?T.green:T.red} fontSize="10">{!isNS?"🟢":"🔴"}</text><text x="250" y="108" textAnchor="middle" fill={!isNS?T.green:T.red} fontSize="10">{!isNS?"🟢":"🔴"}</text>
{Array.from({length:Math.min(qs.N,6)}).map((_,i)=><rect key={"cn"+i} x="130" y={74-i*13} width="16" height="9" rx="3" fill={T.blue} opacity=".6"/>)}{Array.from({length:Math.min(qs.S,6)}).map((_,i)=><rect key={"cs"+i} x="154" y={215+i*13} width="16" height="9" rx="3" fill={T.blue} opacity=".6"/>)}{Array.from({length:Math.min(qs.W,6)}).map((_,i)=><rect key={"cw"+i} x={74-i*13} y="130" width="9" height="16" rx="3" fill={T.blue} opacity=".6"/>)}{Array.from({length:Math.min(qs.E,6)}).map((_,i)=><rect key={"ce"+i} x={215+i*13} y="154" width="9" height="16" rx="3" fill={T.blue} opacity=".6"/>)}
</svg></Panel>
<div style={{display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"}}><span style={{fontSize:11,color:T.sub}}>🟢 Green time</span><input type="range" min="3" max="10" value={gl} step="1" onChange={e=>setGl(+e.target.value)} style={{flex:"1 1 60px",maxWidth:100,accentColor:T.blue}}/><span style={{fontSize:12,fontWeight:600,color:T.blue}}>{gl}s</span>
<Btn onClick={()=>setOn(!on)} on={on} color={on?T.amber:T.green} big>{on?"⏸ Pause":"▶ Run"}</Btn><Btn onClick={step}>⏭</Btn><Btn onClick={reset}>🔄</Btn></div><Log items={log}/></div>}

function HVAC(){const init=[{n:"Lobby",ic:"🏢",temp:22,tgt:22,on:false,occ:3},{n:"Office A",ic:"💼",temp:23,tgt:22,on:false,occ:5},{n:"Office B",ic:"💼",temp:21,tgt:22,on:false,occ:2},{n:"Server Room",ic:"🖥️",temp:25,tgt:20,on:true,occ:0}];
const[zs,setZs]=useState(init);const[clk,setClk]=useState(0);const[log,setLog]=useState([]);const[run,setRun]=useState(false);const[energy,setEnergy]=useState(0);const[mode,setMode]=useState("comfort");const ir=useRef(null);
const step=useCallback(()=>{setClk(c=>c+1);setZs(prev=>{const nz=prev.map(z=>({...z}));const ev=[];const t=clk+1;for(const z of nz){const eff=mode==="eco"?z.tgt+2:z.tgt;if(Math.random()<0.12){const d=Math.random()<0.5?1:-1;z.occ=Math.max(0,Math.min(10,z.occ+d));if(d>0)ev.push({t:t+"s",m:"👤 "+z.n+": person entered ("+z.occ+")",c:T.blue})}z.temp=Math.round((z.temp+z.occ*0.25+(Math.random()-0.3)*0.4-(z.on?1.4:0))*10)/10;if(!z.on&&z.temp>eff+1){z.on=true;ev.push({t:t+"s",m:"❄️ "+z.n+": AC ON ("+z.temp+"°C too hot)",c:T.teal})}else if(z.on&&z.temp<=eff){z.on=false;ev.push({t:t+"s",m:"☀️ "+z.n+": AC OFF (reached target)",c:T.amber})}}setEnergy(e=>e+nz.filter(z=>z.on).length);if(ev.length)setLog(l=>[...l,...ev].slice(-50));return nz})},[clk,mode]);
useEffect(()=>{if(run)ir.current=setInterval(step,600);else clearInterval(ir.current);return()=>clearInterval(ir.current)},[run,step]);const reset=()=>{setRun(false);setClk(0);setLog([]);setEnergy(0);setZs(init)};
return <div><Tip><strong>How it works:</strong> Each room has a thermostat. People generate heat — the more people, the faster the temperature rises. When temperature exceeds the target, AC turns on automatically and cools the room. Eco mode tolerates 2°C warmer to save energy.</Tip>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:10,marginBottom:14}}>{zs.map((z,i)=>{const tc=z.temp>z.tgt+2?T.red:z.temp>z.tgt?T.amber:T.green;return <Panel key={i} glow={z.on?T.teal+"20":undefined} style={{padding:"14px 12px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}><span style={{fontSize:20}}>{z.ic}</span>{z.on?<Badge color={T.teal}>❄️ COOLING</Badge>:<Badge color={T.dim}>OFF</Badge>}</div><div style={{fontSize:12,fontWeight:600,color:T.text}}>{z.n}</div><div style={{fontSize:32,fontWeight:700,color:tc,lineHeight:1.1,margin:"6px 0"}}>{z.temp}°</div><div style={{fontSize:10,color:T.sub}}>🎯 Target: {z.tgt}°C · 👥 {z.occ}</div><Bar value={z.temp-15} max={15} color={tc} h={4}/></Panel>})}</div>
<div style={{display:"flex",gap:8,marginBottom:14,flexWrap:"wrap"}}><Panel style={{flex:1,padding:10,textAlign:"center"}}><Num icon="⏱" label="Time" value={clk} unit="s"/></Panel><Panel style={{flex:1,padding:10,textAlign:"center"}}><Num icon="⚡" label="Energy" value={energy} unit="kWh" color={T.amber}/></Panel><Panel style={{flex:1,padding:10,textAlign:"center"}}><Num icon="❄️" label="Active ACs" value={zs.filter(z=>z.on).length+"/"+zs.length} color={T.teal}/></Panel></div>
<div style={{display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"}}><Btn onClick={()=>setMode(m=>m==="comfort"?"eco":"comfort")} on color={mode==="eco"?T.green:T.blue}>{mode==="eco"?"🌿 Eco":"❄️ Comfort"}</Btn><Btn onClick={()=>setRun(!run)} on={run} color={run?T.amber:T.green} big>{run?"⏸ Pause":"▶ Run"}</Btn><Btn onClick={step}>⏭</Btn><Btn onClick={reset}>🔄</Btn></div><Log items={log}/></div>}

function Warehouse(){const init=[{id:"Robot 1",ic:"🤖",st:"idle",bat:100,done:0,task:null},{id:"Robot 2",ic:"🤖",st:"idle",bat:95,done:0,task:null},{id:"Robot 3",ic:"🤖",st:"idle",bat:88,done:0,task:null}];
const[bots,setBots]=useState(init);const[tq,setTq]=useState([]);const[clk,setClk]=useState(0);const[log,setLog]=useState([]);const[run,setRun]=useState(false);const[done,setDone]=useState(0);const[rate,setRate]=useState(3);const ir=useRef(null);const tid=useRef(0);
const step=useCallback(()=>{setClk(c=>c+1);const t=clk+1;const ev=[];if(Math.random()<rate/10){const types=["Pick shelf A→dock","Pack items→box","Sort returns","Load truck"];const task={id:++tid.current,type:types[Math.floor(Math.random()*types.length)],time:3+Math.floor(Math.random()*3)};setTq(q=>[...q,task]);ev.push({t:t+"s",m:"📋 New order #"+task.id+": "+task.type,c:T.blue})}setBots(prev=>{const nb=prev.map(b=>({...b}));for(const b of nb){if(b.st==="working"&&b.task){b.task.time--;b.bat=Math.max(0,b.bat-2);if(b.task.time<=0){b.st="idle";b.done++;setDone(d=>d+1);ev.push({t:t+"s",m:"✅ "+b.id+" finished: "+b.task.type,c:T.green});b.task=null}}if(b.st==="charging"){b.bat=Math.min(100,b.bat+12);if(b.bat>=100){b.st="idle";ev.push({t:t+"s",m:"🔋 "+b.id+" fully charged!",c:T.green})}}if(b.st==="idle"&&b.bat<20){b.st="charging";ev.push({t:t+"s",m:"🔌 "+b.id+" low battery → charging",c:T.amber})}if(b.st==="idle"&&b.bat>=20){setTq(q=>{if(q.length>0){const[task,...rest]=q;b.st="working";b.task={...task};ev.push({t:t+"s",m:"🤖 "+b.id+" picking up: "+task.type,c:T.purple});return rest}return q})}}return nb});if(ev.length)setLog(l=>[...l,...ev].slice(-50))},[clk,rate]);
useEffect(()=>{if(run)ir.current=setInterval(step,700);else clearInterval(ir.current);return()=>clearInterval(ir.current)},[run,step]);const reset=()=>{setRun(false);setClk(0);setLog([]);setDone(0);setTq([]);tid.current=0;setBots(init)};
return <div><Tip><strong>How it works:</strong> Orders arrive in a task queue. Idle robots grab the next task. When a robot's battery drops below 20%, it goes to charge first. Watch how the fleet juggles tasks and battery management!</Tip>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:10,marginBottom:14}}>{bots.map((b,i)=>{const bc=b.bat>50?T.green:b.bat>20?T.amber:T.red;return <Panel key={i} glow={b.st==="working"?T.amber+"20":b.st==="charging"?T.green+"20":undefined} style={{padding:14}}><div style={{fontSize:30,textAlign:"center"}}>{b.ic}</div><div style={{fontSize:12,fontWeight:600,color:T.text,textAlign:"center"}}>{b.id}</div><div style={{textAlign:"center",marginTop:6}}>{b.st==="working"?<Badge color={T.amber}>⚙️ Working</Badge>:b.st==="charging"?<Badge color={T.green}>🔌 Charging</Badge>:<Badge color={T.dim}>💤 Idle</Badge>}</div>{b.task&&<div style={{fontSize:10,color:T.sub,textAlign:"center",marginTop:6}}>📦 {b.task.type}<br/>⏳ {b.task.time}s left</div>}<div style={{marginTop:8}}><Bar value={b.bat} max={100} color={bc} h={6}/></div><div style={{fontSize:10,color:bc,textAlign:"center",marginTop:3}}>🔋 {b.bat}%</div></Panel>})}</div>
<div style={{display:"flex",gap:8,marginBottom:14,flexWrap:"wrap"}}><Panel style={{flex:1,padding:10,textAlign:"center"}}><Num icon="📋" label="Queue" value={tq.length} color={tq.length>5?T.red:T.blue}/></Panel><Panel style={{flex:1,padding:10,textAlign:"center"}}><Num icon="✅" label="Done" value={done} color={T.green}/></Panel><Panel style={{flex:1,padding:10,textAlign:"center"}}><Num icon="⏱" label="Time" value={clk} unit="s"/></Panel></div>
<div style={{display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"}}><span style={{fontSize:11,color:T.sub}}>📈 Orders</span><input type="range" min="1" max="8" value={rate} step="1" onChange={e=>setRate(+e.target.value)} style={{flex:"1 1 60px",maxWidth:100,accentColor:T.blue}}/><span style={{fontSize:12,fontWeight:600,color:T.blue}}>{rate}/10</span><Btn onClick={()=>setRun(!run)} on={run} color={run?T.amber:T.green} big>{run?"⏸ Pause":"▶ Run"}</Btn><Btn onClick={step}>⏭</Btn><Btn onClick={reset}>🔄</Btn></div><Log items={log}/></div>}

function Cloud(){const[inst,setInst]=useState(2);const[cpu,setCpu]=useState(25);const[q,setQ]=useState(0);const[clk,setClk]=useState(0);const[log,setLog]=useState([]);const[run,setRun]=useState(false);const[done,setDone]=useState(0);const[drop,setDrop]=useState(0);const[pat,setPat]=useState("steady");const[thr,setThr]=useState(70);const ir=useRef(null);
const step=useCallback(()=>{setClk(c=>{const t=c+1;const ev=[];const load=pat==="steady"?3:pat==="spike"?(t%20<5?9:2):(Math.sin(t/5)*3+4);const nr=Math.max(0,Math.floor(load+(Math.random()-0.5)*2));setQ(qq=>{let nq=qq+nr;const cap=inst*3;const s=Math.min(nq,cap);setDone(d=>d+s);nq-=s;if(nq>20){const d=nq-20;setDrop(dd=>dd+d);nq=20;ev.push({t:t+"s",m:"🔴 "+d+" requests dropped! (overloaded)",c:T.red})}return nq});const nc=Math.min(100,Math.round((q/(inst*5+1))*100+Math.random()*10));setCpu(nc);if(nc>thr&&inst<8){setInst(i=>i+1);ev.push({t:t+"s",m:"⬆️ Added server! Now "+(inst+1)+" (CPU "+nc+"%)",c:T.green})}else if(nc<thr-30&&inst>1){setInst(i=>i-1);ev.push({t:t+"s",m:"⬇️ Removed server → "+(inst-1)+" (CPU "+nc+"%)",c:T.amber})}if(ev.length)setLog(l=>[...l,...ev].slice(-50));return t})},[inst,q,pat,thr]);
useEffect(()=>{if(run)ir.current=setInterval(step,500);else clearInterval(ir.current);return()=>clearInterval(ir.current)},[run,step]);const reset=()=>{setRun(false);setClk(0);setInst(2);setCpu(25);setQ(0);setLog([]);setDone(0);setDrop(0)};const cc=cpu>80?T.red:cpu>thr?T.amber:T.green;
return <div><Tip><strong>How it works:</strong> User requests come in and are handled by servers. When CPU gets too high, the system adds more servers automatically. When it drops, it removes extras to save cost. Try "Spike" to see it react to sudden traffic!</Tip>
<div style={{display:"flex",gap:8,marginBottom:14,flexWrap:"wrap"}}>{[{ic:"🖥️",l:"Servers",v:inst,c:T.blue},{ic:"📊",l:"CPU",v:cpu+"%",c:cc},{ic:"📥",l:"Queue",v:q,c:q>10?T.red:T.sub},{ic:"✅",l:"Processed",v:done,c:T.green}].map((m,i)=><Panel key={i} style={{flex:"1 1 70px",padding:"10px 8px",textAlign:"center"}}><Num icon={m.ic} label={m.l} value={m.v} color={m.c}/></Panel>)}</div>
<Panel style={{marginBottom:14,padding:16}}><div style={{fontSize:11,color:T.sub,marginBottom:10}}>🖥️ Active Servers ({inst})</div><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:12}}>{Array.from({length:inst}).map((_,i)=><div key={i} style={{width:48,height:48,borderRadius:10,display:"flex",alignItems:"center",justifyContent:"center",background:T.panel,border:"1px solid "+cc+"30",fontSize:22,boxShadow:"0 0 12px "+cc+"10",transition:"all 0.3s"}}>🖥️</div>)}</div>
<div style={{display:"flex",justifyContent:"space-between",fontSize:10,color:T.dim,marginBottom:3}}><span>CPU Load</span><span style={{color:cc,fontWeight:600}}>{cpu}%</span></div><div style={{height:10,background:T.bg,borderRadius:5,overflow:"hidden",position:"relative"}}><div style={{height:"100%",width:cpu+"%",background:"linear-gradient(90deg,"+T.green+","+(cpu>50?T.amber:T.green)+","+(cpu>75?T.red:T.amber)+")",borderRadius:5,transition:"width 0.4s"}}/><div style={{position:"absolute",left:thr+"%",top:0,bottom:0,width:2,background:T.text,opacity:.3}}/></div><div style={{fontSize:9,color:T.dim,marginTop:2}}>▲ Auto-scale at {thr}%</div></Panel>
<div style={{display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"}}><span style={{fontSize:11,color:T.sub}}>Traffic:</span>{["steady","spike","wave"].map(p=><Btn key={p} onClick={()=>setPat(p)} on={pat===p}>{p==="steady"?"📊 Steady":p==="spike"?"⚡ Spike":"🌊 Wave"}</Btn>)}<span style={{fontSize:11,color:T.sub}}>Scale at</span><input type="range" min="50" max="90" value={thr} step="5" onChange={e=>setThr(+e.target.value)} style={{width:60,accentColor:T.blue}}/><span style={{fontSize:12,fontWeight:600,color:T.blue}}>{thr}%</span><Btn onClick={()=>setRun(!run)} on={run} color={run?T.amber:T.green} big>{run?"⏸":"▶"}</Btn><Btn onClick={step}>⏭</Btn><Btn onClick={reset}>🔄</Btn></div><Log items={log}/></div>}

const TABS=[{k:"factory",t:"🏭 Factory",c:Factory},{k:"traffic",t:"🚦 Traffic",c:Traffic},{k:"hvac",t:"🌡️ HVAC",c:HVAC},{k:"warehouse",t:"🤖 Robots",c:Warehouse},{k:"cloud",t:"☁️ Cloud",c:Cloud}];
export default function App(){const[tab,setTab]=useState("factory");const S=TABS.find(t=>t.k===tab);const C=S.c;
return <div style={{background:T.bg,minHeight:"100vh",padding:"16px 12px",fontFamily:"'DM Sans',system-ui,sans-serif",color:T.text}}>
<div style={{maxWidth:760,margin:"0 auto"}}><div style={{textAlign:"center",marginBottom:16}}><h1 style={{fontSize:20,fontWeight:700,margin:0}}>⚡ Interactive DES Simulator</h1><p style={{fontSize:12,color:T.sub,margin:"4px 0 0"}}>Watch how automated systems work in real time</p></div>
<div style={{display:"flex",gap:0,marginBottom:18,background:T.panel,borderRadius:10,padding:3,border:"1px solid "+T.border}}>{TABS.map(t=><button key={t.k} onClick={()=>setTab(t.k)} style={{flex:"1 1 0",padding:"8px 4px",fontSize:12,fontWeight:tab===t.k?600:400,background:tab===t.k?T.card:"transparent",color:tab===t.k?T.text:T.dim,border:"none",borderRadius:8,cursor:"pointer",fontFamily:"inherit",transition:"all 0.2s",minWidth:0,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{t.t}</button>)}</div>
<C/></div></div>}
